// This is the main Frida Java JNI implementation file
// It includes all the JNI implementations for Frida Java bindings

#include "frida_common.c"
#include "frida_jni.c"
#include "application_jni.c"
#include "application_query_options_jni.c"
#include "child_jni.c"
#include "device_manager_jni.c"
#include "device_jni.c"
#include "device_list_jni.c"
#include "frontmost_query_options_jni.c"
#include "process_jni.c"
#include "process_list_jni.c"
#include "process_match_options_jni.c"
#include "process_query_options_jni.c"
#include "remote_device_options_jni.c"
#include "script_jni.c"
#include "session_jni.c"
#include "session_options_jni.c"
#include "spawn_jni.c"
