<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.axelkoolhaas</groupId>
    <artifactId>frida-java-parent</artifactId>
    <version>2.0</version>
    <packaging>pom</packaging>

    <name>Frida Java Parent</name>
    <description>Parent project for Frida Java bindings and examples</description>
    <url>https://github.com/shoaloak/frida-java</url>
    <developers>
        <developer>
            <id>shoaloak</id>
            <name>Axel Koolhaas</name>
            <email>dev@axelkoolhaas.nl</email>
            <url>https://axelkoolhaas.nl</url>
            <roles>
                <role>developer</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <modules>
        <module>frida-java-core</module>
        <module>frida-java-examples</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.10.0</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


</project>
