name: Build Frida

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-frida-linux-arm64:
    runs-on: ubuntu-24.04-arm
    outputs:
      artifact-path: ${{ steps.upload-frida.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Linux so
        run: ./frida-java-core/scripts/build-frida-linux.sh

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-core-linux-arm64
          path: ./frida-java-core/frida-devkit/libfrida-core-arm64.so

  build-frida-linux-x64:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-frida.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Linux so
        run: ./frida-java-core/scripts/build-frida-linux.sh

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-core-linux-x64
          path: ./frida-java-core/frida-devkit/libfrida-core-x86_64.so

  build-frida-macos:
    runs-on: macos-latest
    outputs:
      artifact-path: ${{ steps.upload-frida.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build universal macOS dylib
        run: ./frida-java-core/scripts/build-frida-macos.sh

      - name: Upload universal dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: frida-core-macos-universal
          path: "./frida-java-core/frida-devkit/libfrida-core.dylib"

  build-frida-windows-arm64:
    runs-on: windows-11-arm
    outputs:
      artifact-path: ${{ steps.upload-frida.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build windows dll
        shell: powershell
        run: ./frida-java-core/scripts/build-frida-windows.ps1

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-core-windows-arm64
          path: ./frida-java-core/frida-devkit/libfrida-core-arm64.dll

  build-frida-windows-x64:
    runs-on: windows-latest
    outputs:
      artifact-path: ${{ steps.upload-frida.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build windows dll
        shell: powershell
        run: ./frida-java-core/scripts/build-frida-windows.ps1

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-core-windows-x64
          path: ./frida-java-core/frida-devkit/libfrida-core-x86_64.dll

  build-frida-java:
    needs: [build-frida-linux-arm64, build-frida-linux-x64, build-frida-macos, build-frida-windows-arm64, build-frida-windows-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Download Linux ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: frida-core-linux-arm64
          path: ./frida-java-core/native/

      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: frida-core-linux-x64
          path: ./frida-java-core/native/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: frida-core-macos-universal
          path: ./frida-java-core/native/

      - name: Download Windows ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: frida-core-windows-arm64
          path: ./frida-java-core/native/

      - name: Download Windows x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: frida-core-windows-x64
          path: ./frida-java-core/native/

      - name: Build bindings with Maven and package JAR
        run: mvn clean compile package -pl frida-java-core -am

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: frida-java-core
          path: |
            ./frida-java-core/target/frida-java-*.jar
            ./frida-java-core/target/frida-java-*.pom